### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by KarzoKalori** [j3r3m1/urock_prepare#2]
Not sure if this is a bug in Java.

![spara2](https://user-images.githubusercontent.com/83512843/202414754-c0f7abf7-14ec-4fef-b858-64750ce5a001.jpg)

**Comment by j3r3m1** [comment]
There is no Java installation needed for this plugin, it is 100% QGIS. I suppose the file described in the error does not exist in your computer (you have to retry it before to know since temporary data may have been deleted if you turn off your session) ?

Can you attach all the input files you used ?

**Comment by KarzoKalori** [comment]
Ok interesting.. I am attaching the data I used to run it.

[dataURock.zip](https://github.com/j3r3m1/gen_buildveg_vlayers/files/10032506/dataURock.zip)

**Comment by j3r3m1** [comment]
Can you share your "build_clip_efterdsm.shp" file ?

**Comment by KarzoKalori** [comment]
Of course.  "build_clip_efterdsm.shp" is used to cut out the buildings that extended outside the raster files (dsm them and them).

[Urockdata2.zip](https://github.com/j3r3m1/gen_buildveg_vlayers/files/10039409/Urockdata2.zip)

**Comment by j3r3m1** [comment]
OK no trouble on my computer with the following config:
{ 'BUILDINGS_WITH_HEIGHT' : '/tmp/test_build.shp', 'HEIGHT_VEG_FIELD' : '', 'INPUT_BUILD_DEM' : '/tmp/Urockdata/DEM_KRbig.tif', 'INPUT_BUILD_DSM' : '/tmp/Urockdata/DSM_KRbig.tif', 'INPUT_BUILD_FOOTPRINT' : '/tmp/Urockdata/build_clip_efterdsm.shp', 'INPUT_VEG_CDSM' : '/tmp/Urockdata/CDSM_KRbig.asc', 'INPUT_VEG_POINTS' : None, 'LOAD_OUTPUT' : True, 'OUTPUT_BUILD_HEIGHT_FIELD' : 'ROOF_HEIGHT', 'OUTPUT_VEG_HEIGHT_FIELD' : 'VEG_HEIGHT', 'RADIUS_VEG_FIELD' : '', 'VEGETATION_ASPECT' : '0.75', 'VEGETATION_WITH_HEIGHT' : '/tmp/test_veg.shp' }

I have double checked that the version I use is the same as the github one, it is. Can you retry and check that the file not found really not exist on your computer ?

**Comment by KarzoKalori** [comment]
I'm using the latest one available here on Github. But the folder it refers to is empty. What should be in that folder?

![tomt](https://user-images.githubusercontent.com/83512843/202667030-5ebbc586-44b6-40e9-9fed-5ea2f7119f27.jpg)

**Comment by j3r3m1** [comment]
I have uploaded a new version of the plugin with only native functions (saga were used before). It might solve your problem. Can you have a check ?

**Comment by j3r3m1** [comment]
(the modifications of the code are here (only a reminder for me: https://github.com/j3r3m1/urock_prepare/commit/f356b4477fceb804c6c2245a3b127eccdc838529))

**Comment by KarzoKalori** [comment]
It works flawlessly! Good work!

**Comment by j3r3m1** [comment]
Yes .shp is possible, you just have to specify that when you specify where you want to save the file.

**Comment by KarzoKalori** [comment]
You mean when you tick "Save 2D wind field as vector file(s)"? It doesn't generate any shp file for me.

**Comment by j3r3m1** [comment]
Have a try using the new repo position then it might have be solved by BigLimp:
https://github.com/UMEP-dev/UMEP-processing
